# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SB FreeAPI_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SB FreeAPI_App

	pod 'Alamofire'

end
